services:
  - type: web
    name: Seva-Management-App-  # Match the Render service name
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_API_KEY
        sync: false
      - key: SUPABASE_TABLE
        sync: false
      - key: POSTGRES_URL  # ✅ Updated from DATABASE_URL
        sync: false
